"""auto_20251029_204104

Revision ID: 6fa70c8edae2
Revises: f737c540ef7f
Create Date: 2025-10-29 20:41:04.984744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa70c8edae2'
down_revision: Union[str, Sequence[str], None] = 'f737c540ef7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index('ix_events_latitude', 'events', ['latitude'], unique=False)
    op.create_index('ix_events_longitude', 'events', ['longitude'], unique=False)
    op.create_index('ix_events_start_time', 'events', ['start_time'], unique=False)
    op.drop_column('events', 'venue')
    op.add_column('users', sa.Column('location_address', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('location_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('location_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location_longitude')
    op.drop_column('users', 'location_latitude')
    op.drop_column('users', 'location_address')
    op.add_column('events', sa.Column('venue', sa.VARCHAR(length=255), nullable=False))
    op.drop_index('ix_events_start_time', table_name='events')
    op.drop_index('ix_events_longitude', table_name='events')
    op.drop_index('ix_events_latitude', table_name='events')
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'latitude')
    op.drop_column('events', 'address')
    # ### end Alembic commands ###
